#!/bin/bash

# Get pod information and extract relevant details
pod_info=$(microk8s kubectl get pods -o wide --no-headers)

# Create or overwrite the hosts file
echo "# Hosts file generated by script" > hosts

# Loop through each line of the pod information
while IFS= read -r line; do
    # Extract pod name and IP address
    pod_name=$(echo "$line" | awk '{print $1}')
    # Extract the IP address from the sixth field
    ip_address=$(echo "$line" | awk '{print $6}')

    # Check if the IP address is valid
    if ! [[ "$ip_address" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        # If not valid, use the IP address from the eighth field
        ip_address=$(echo "$line" | awk '{print $8}')
    fi

    # Extract the hostname (remove everything after the first hyphen)
    hostname=$(echo "$pod_name" | awk -F- '{print $1}')

    # Handle special case for nodemanager1
    if [ "$hostname" == "nodemanager1" ]; then
        hostname="nodemanager"
    fi

    # Append the entry to the hosts file
    echo "$ip_address $hostname" >> hosts
done <<< "$pod_info"

echo "Hosts file created successfully!"

cat hosts

