apiVersion: v1
kind: Service
metadata:
  name: nodemanager1
spec:
  ports:
    - name: "port-13562"
      port: 13562
      targetPort: 13562
    - name: "port-8042"
      port: 8042
      targetPort: 8042
    - name: "port-8040"
      port: 8040
      targetPort: 8040
    - name: "port-38475"
      port: 38475
      targetPort: 38475
  selector:
    io.kompose.service: nodemanager1
status:
  loadBalancer: {}