FROM bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8

RUN echo "deb http://archive.debian.org/debian/ stretch main\ndeb http://archive.debian.org/debian-security stretch/updates main" | tee /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y python3 && \
    apt-get install -y nano