apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert --file docker-compose-old.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  ports:
  - name: "9870"
    port: 9870
    targetPort: 9870
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: namenode
status:
  loadBalancer: {}
