FROM bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8

RUN echo "deb http://archive.debian.org/debian/ stretch main\ndeb http://archive.debian.org/debian-security stretch/updates main" | tee /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y python3 && \
    apt-get install -y nano && \
	apt-get install -y curl && \
	apt-get install -y iputils-ping && \
	apt-get install -y iputils-arping && \
	apt-get install -y net-tools && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/input-500.sh >> /home/input-500.txt && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/input-1000.sh >> /home/input-1000.txt && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/input-5000.sh >> /home/input-5000.txt && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/input-10000.sh >> /home/input-10000.txt && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/exec-input-500.sh >> /home/exec-input-500.sh && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/exec-input-1000.sh >> /home/exec-input-1000.txt && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/exec-input-5000.sh >> /home/exec-input-5000.txt && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/exec-input-10000.sh >> /home/exec-input-10000.txt && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/init-dfs.sh >> /home/init-dfs.sh && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/reducer.py >> /home/reducer.py && \
	curl https://raw.githubusercontent.com/hakidon/docker-hadoop/main/k8s/script/code/mapper.py >> /home/mapper.py &&\
	chmod +x /home/exec-input-500.sh /home/exec-input-1000.txt /home/exec-input-5000.txt /home/exec-input-10000.txt /home/init-dfs.sh


	