apiVersion: v1
kind: Service
metadata:
  name: historyserver
spec:
  ports:
    - name: "port-8188"
      port: 8188
      targetPort: 8188
    - name: "port-10200"
      port: 10200
      targetPort: 10200
  selector:
    io.kompose.service: historyserver
status:
  loadBalancer: {}