apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
spec:
  ports:
    - name: "port-8030"
      port: 8030
      targetPort: 8030
    - name: "port-8031"
      port: 8031
      targetPort: 8031
    - name: "port-8032"
      port: 8032
      targetPort: 8032
    - name: "port-8088"
      port: 8088
      targetPort: 8088
  selector:
    io.kompose.service: resourcemanager
status:
  loadBalancer: {}